.\"
.\" Copyright (c) 2019 Logan Ryan McLintock
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd September 13, 2019
.Dt UTF8COUNT 1
.Os
.Sh NAME
.Nm utf8count
.Nd counts UTF-8 characters
.Sh SYNOPSIS
.Nm utf8count
.Op Ar file
.Sh DESCRIPTION
The
.Nm
utility counts UTF-8 characters.
If no
.Ar file
is given
or
.Ar file
is a single dash
.Pq Sq -
then
.Nm
will read from the standard input.
.Pp
The output appears in three tab separated columns,
with the first column being the Unicode code point in decimal,
the second column the glyph (with ASCII control characters
displayed as their two digit hexadecimal value),
and the third column the count. Only present UTF-8 characters are printed.
.Pp
.Nm
is released under the ISC licence (OpenBSD style).
.Sh EXIT STATUS
.Ex -std utf8count
.Sh EXAMPLES
.Dl $ utf8count myfile
.Sh AUTHORS
.Nm
was written by
.An "Logan Ryan McLintock".
