.\"
.\" Copyright (c) 2019 Logan Ryan McLintock
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd June 12, 2019
.Dt SPOT 1
.Os
.Sh NAME
.Nm spot
.Nd text editor
.Sh SYNOPSIS
.Nm spot
.Op Ar
.Sh DESCRIPTION
.Nm
is a minimalistic text editor that uses the gen, buf and ncurses
libraries.
It has many advanced features:
.Bl -bullet -offset indent
.It
buffer sizes and number of buffers only limited by random access memory,
.It
efficient file reading and writing,
and efficient killregion and yank functions,
.It
automatic row number updating,
.It
intelligent gap increases,
.It
integer overflow protection,
.It
region highlighting,
.It
full editing available in the command line,
.It
and gap buffer independent graphics.
.El
.Pp
.Nm
is released under the ISC licence (OpenBSD style).
.Sh KEY BINDINGS
C-f means press the Control key and the f key simultaneously.
M-f means press the Meta key (or the Alt Key) and the f key simultaneously,
or press the ESC key followed by the f key. The region is the text between
the mark and the cursor. The mark is a location remembered in the buffer.
.Bl -tag -width 10n
.It C-g
Quit from region highlighting or from the command line
.It C-f
Forward character
.It C-b
Backward character
.It C-p
Previous line
.It C-n
Next line
.It C-a
Start of line
.It C-e
End of line
.It M-<
Start of buffer
.It M->
End of buffer
.It M-f
Forward word
.It M-b
Backward word
.It M-}
Forward paragraph
.It M-{
Backward paragraph
.It M-a
Forward sentence
.It M-e
Backward sentence
.It C-v
Page up
.It M-v
Page down
.It M-u
Uppercase word
.It M-l
Lowercase word
.It M-m
Match brace
.It C-d
Delete
.It C-h
Backspace
.It M-t
Trim trailing whitespace
.It C-q
Quote a two digit hexadecimal value
.It C-s
Forward search
.It M-n
Repeat last forward search
.It C-spc
Set mark
.It C-k
Kill to end of line
.It C-u
Uproot (kill to start of line)
.It C-w
Wipe (kill region)
.It M-w
Copy region
.It C-y
Yank (paste) the last killed or copied text
.It C-x i
Insert file
.It C-x C-r
Rename buffer
.It C-x C-s
Save buffer
.It C-x C-f
Open file in new buffer
.It C-x LEFT
Previous buffer
.It C-x RIGHT
Next buffer
.It C-x C-c
Close editor (unsaved modifications will be lost from all buffers)
.El
.Sh EXIT STATUS
.Ex -std spot
.Sh EXAMPLES
.Dl $ spot file1 file2
.Sh SEE ALSO
.Xr ncurses 3
.Sh AUTHORS
.Nm
was written by
.An "Logan Ryan McLintock".
