.\"
.\" Copyright (c) 2019 Logan Ryan McLintock
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd September 13, 2019
.Dt CHARCOUNT 1
.Os
.Sh NAME
.Nm charcount
.Nd counts chars
.Sh SYNOPSIS
.Nm charcount
.Op Ar file
.Sh DESCRIPTION
The
.Nm
utility counts chars.
If no
.Ar file
is given
or
.Ar file
is a single dash
.Pq Sq -
then
.Nm
will read from the standard input.
Non-printable glyphs (including space) are displayed as their
two digit hexadecimal value. The output appears in two tab
separated columns, with the first column being the char and
the second column the count. Only present chars are printed.
.Pp
.Nm
is released under the ISC licence (OpenBSD style).
.Sh EXIT STATUS
.Ex -std charcount
.Sh EXAMPLES
.Dl $ charcount myfile
.Sh AUTHORS
.Nm
was written by
.An "Logan Ryan McLintock".
